name: Format code

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - run: npx textlint ./contents/**/*.md >> ./.textlint.log
      - if: ${{ failure() }}
        run: gh pr comment --body-file ./.textlint.log "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
